# Generated by Django 3.0.6 on 2020-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surflineId', models.CharField(max_length=100)),
                ('spotName', models.CharField(max_length=100)),
            ],
        ),
    ]
