# Generated by Django 3.0.6 on 2020-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfinfo', '0002_surfspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfsession',
            name='spotUtcOffset',
            field=models.DecimalField(decimal_places=2, default=-7, max_digits=4),
            preserve_default=False,
        ),
    ]
