# Generated by Django 3.0.6 on 2020-06-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfinfo', '0003_surfsession_spotutcoffset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
